### PR TITLE
Update Dactyl Original preset

### PR DESCRIPTION
**Pull request by dunk2k**
Reference: https://github.com/adereth/dactyl-keyboard

### CODE REVIEW

**Comment by rianadon** [comment]
Is this equivalent? https://ryanis.cool/dactyl/#original:ChIIBhABGAEiA2JveCoDc2l4MAA=

I changed Thumb Key Count to 6. I'm not sure if anything else is missing.

**Comment by dunk2k** [comment]
That's correct, the "six" key thumb cluster is correct for the Original Dactyl.
And no other dimensional settings between the Dactyl Lightcycle and Original Dactyl are changed; Dactyl Lightcycle is essentially an Original Dactyl with number row omitted and a 5 key thumb cluster 😊

Speaking of thumb clusters, is there a means to denote which key positions are of a particular key cap size? I.e. the Dactyl Original "five" thumb cluster makes clever use of different keycap sizes.
comparison  
*Top: Dactyl Lightcycle  
Bottom: Dactyl Original*

**Comment by rianadon** [comment]
My bad I did not realize at all this is a pull request. I see we agree what needs to be changed :)

> Speaking of thumb clusters, is there a means to denote which key positions are of a particular key cap size? I.e. the Dactyl Original "five" thumb cluster makes clever use of different keycap sizes.

The original dactyl code already has code for generating keycaps, but the option for showing them never made it through to the UI. I'll add it 👍

I don't know where things diverged, but the 5-key layout looks different than your screenshot.

image

**Comment by rianadon** [comment]
image

Now *this* looks more like it.

**Pull request merged**
